---

- name: create cert dir
  file:
    state: directory
    path: "{{ src_dir }}/certificates"
    mode: "0700"

- name: copy cert and private key to semi-secure location
  copy:
    src: "{{ ca_dir }}/{{ item }}"
    dest: "{{ src_dir }}/certificates"
  with_items:
    - rootCA.crt
    - rootCA.key

- name: delete existing secret (errors non-fatal)
  ignore_errors: yes
  command: kubectl -n topolvm-system delete secret mutatingwebhook

- name: install secret
  command: kubectl -n topolvm-system create secret tls mutatingwebhook --cert="{{ src_dir }}/certificates/rootCA.crt" --key="{{ src_dir }}/certificates/rootCA.key"
